# Generated by Django 3.0.3 on 2020-12-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleave',
            name='leave_status',
            field=models.CharField(choices=[('APPROAVED', 'Approaved'), ('WAITING', 'Waiting'), ('REJECTED', 'Rejected')], default='Waiting', max_length=25),
        ),
    ]
