# Generated by Django 3.0.3 on 2020-12-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_employeeleave_leave_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleave',
            name='leave_status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('APPROAVED', 'Approaved'), ('REJECTED', 'Rejected')], default='Waiting', max_length=25),
        ),
    ]
