# Generated by Django 3.0.3 on 2020-12-28 08:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('emp_number', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=50)),
                ('place_of_birth', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('mobile_number', models.CharField(max_length=150)),
                ('id_type', models.CharField(choices=[('NATIONAL', 'National'), ('PASSPORT', 'Passport')], max_length=10)),
                ('id_number', models.CharField(max_length=14)),
                ('hire_date', models.DateField()),
                ('leave_balance', models.IntegerField(default=21)),
                ('social_status', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married')], max_length=10)),
                ('is_insured', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('has_medical', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('department_desc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('CASUAL', 'Casual'), ('TRAINEE', 'Trainee'), ('CONTRACTOR', 'Contractor')], max_length=15)),
                ('contract_start_date', models.DateField(default=datetime.datetime.now)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Department')),
                ('emp_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_requests_created', to='employee.Employee')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Position')),
            ],
        ),
    ]
