# Generated by Django 3.0.3 on 2020-12-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('emp_number', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=50)),
                ('place_of_birth', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('mobile_number', models.CharField(max_length=150)),
                ('id_type', models.CharField(choices=[('NATIONAL', 'national'), ('PASSPORT', 'passport')], max_length=10)),
                ('id_number', models.IntegerField()),
                ('hire_date', models.DateField()),
                ('social_status', models.CharField(choices=[('SINGLE', 'single'), ('MARRIED', 'married')], max_length=10)),
                ('is_insured', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('has_medical', models.BooleanField()),
            ],
        ),
    ]
