# Generated by Django 3.0.3 on 2021-01-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='has_medical',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_number',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_type',
            field=models.CharField(choices=[('NATIONAL', 'National'), ('PASSPORT', 'Passport')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_insured',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='leave_balance',
            field=models.IntegerField(default=21, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile_number',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nationality',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='place_of_birth',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='social_status',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married')], max_length=10, null=True),
        ),
    ]
