# Generated by Django 3.0.3 on 2020-12-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_number',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_type',
            field=models.CharField(choices=[('NATIONAL', 'National'), ('PASSPORT', 'Passport')], max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='social_status',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married')], max_length=10),
        ),
    ]
